# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicker',
            name='name',
            field=models.CharField(default='Clicker', max_length=50),
        ),
    ]
